services:
  database:
    image: postgres:14.1-alpine
    restart: always
    environment:
        - POSTGRES_USER=postgres
        - POSTGRES_PASSWORD=postgres
    ports:
      - '7898:5432'
    volumes:
      - database:/var/lib/postgresql/data
volumes:
    database:
        driver: local